### ISSUE TITLE
Bucket access AWS region related problem

### ISSUE THREAD

**Issue by sciabarra** [nimbella/nimbella-sdk-python#11]
**Describe the bug**
If nimbella is deployed in AWS in a generic region (for example `eu-south-1`) you get an error

```
An error occurred (IllegalLocationConstraintException) when calling the PutObject operation: The eu-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```

**To Reproduce**
1. Install nimbella in AWS in another region (for example EKSItaly is in eu-south-1)
2. Run this code:
```
def main(arg):
    try:
        bucket = nimbella.storage()
        filename = "test.txt"
        file = bucket.file(filename)
        file.save('Expected %s contents' % filename, 'text/plain')
        return { "ok": True}
    except Exception as e:
        return { "error": str(e) }
```

3.

**Expected behavior**
ok: True

**Screenshots**

Extra informations:

This is what the __NIM_STORAGE_KEY looks like (stripped down of credentials)

```
NIM_STORAGE_KEY="{\"provider\":\"@nimbella/storage-s3\",\"region\":\"eu-south-1\",\"endpoint\":\"\",\"weburl\":\"https://iogw-eksitaly.nimbella.io\",\"cloudfrontId\":\"XXXX\",\"iamUser\":\"app-buckets-iogw-Y0avZmVH\",\"policyArn\":\"arn:aws:iam::332320267357:policy/app-buckets-iogw-Y0avZmVH\",\"credentials\":{\"accessKeyId\":\"XXX\",\"secretAccessKey\":\"jXXX"}}"
```

**Comment by jthomas** [comment]
Thanks for finding this @sciabarra. Will have a look...

**Comment by sciabarracom** [comment]
Check PR#12 for a fix

**Comment by jthomas** [comment]
Having a look at this again.... I appreciate the fix in https://github.com/nimbella/nimbella-sdk-python/pull/12 but before merging I want to replicate the issue preventing the more obvious fix ("pass region") and see if I can fix it. Otherwise - we'll go with what you have... Won't spend too much time on it.

**Comment by rabbah** [comment]
Thanks James - I too am hoping we can fix this issue more directly rather than through the env var. 👍

**Comment by sciabarra** [comment]
The issue can be easily replicated deploying in a region non us-east as looks like buckets in that regions are special and does not require the region parameters.

The issue can be fixed without the env vars changing the api and passing the region to the Session object. However honestly I tried and it did not work...

**Comment by jthomas** [comment]
I think I've managed to fix this at the source - see https://github.com/nimbella/nimbella-sdk-python/pull/13
@sciabarra does this work for you? I've tried with the credentials you gave me and had no issues. 

Here's the test file I used locally 
```python
import nimbella

bucket = nimbella.storage()
filename = "test.txt"
file = bucket.file(filename)
file.save('Expected %s contents' % filename, 'text/plain')
```

with the __OW_NAMESPACE, __OW_API_HOST and __NIM_STORAGE_KEY env variables set to the parameters you gave me.

**Comment by sciabarra** [comment]
I need to rebuild EKS with your PR to test - will do
